## 6-е домашнее задание - Библиотека numpy

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


## Белов Никита НПМбд-01-19

In [2]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [9]:
a = np.linspace(-1.3, 2.5, 64)
a

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [16]:
print('Введите n: ')
n = int(input())
a = np.array([1,2,3]*n)
a

Введите n: 
2


array([1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [17]:
a = np.arange(1,21)
b = a[::2]
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [24]:
a = np.zeros(100).reshape(10,10)
b = np.pad(a, pad_width=1, constant_values=1)
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [32]:
a = np.ones(64).reshape(8,8)
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [52]:
def func_i_plus_j(n):
    a = np.zeros((n,n))
    a[0,:] = np.arange(1, n+1)
    for i in range(1, n):
        a[i,:] = a[i-1,:]+1
    return a
func_i_plus_j(5)

array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.],
       [5., 6., 7., 8., 9.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [3]:
b = np.arange(10)
M = np.ones((10,10))
print('M*M: ',np.dot(M,M),'M*В: ',np.dot(M,b),'B*В: ',np.dot(b,b), sep='\n')

M*M: 
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
M*В: 
[45. 45. 45. 45. 45. 45. 45. 45. 45. 45.]
B*В: 
285


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [85]:
a = np.arange(0,1,0.05)
b = np.cos(a[::])
c = np.sin(a[::])
d = np.vstack((b,c))
d

array([[1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
        0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
        0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
        0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309],
       [0.        , 0.04997917, 0.09983342, 0.14943813, 0.19866933,
        0.24740396, 0.29552021, 0.34289781, 0.38941834, 0.43496553,
        0.47942554, 0.52268723, 0.56464247, 0.60518641, 0.64421769,
        0.68163876, 0.71735609, 0.75128041, 0.78332691, 0.8134155 ]])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [94]:
a = (3+1)*np.random.random_sample(size = (3,5)) - 1
a

array([[ 1.1978053 ,  0.01895813,  0.37093147,  1.76014411, -0.17380385],
       [ 1.60307373, -0.04409045, -0.29083426,  2.82286041,  1.9585593 ],
       [ 1.98737691,  1.3071716 ,  1.1193377 ,  2.72595331,  1.47527694]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [6]:
a = np.random.random(size = (5,5))
a_sum = a.sum()
summa_strok = np.zeros(5)
summa_strok[:] = a[:].sum(axis = 1)
summa_stolbcov = np.zeros(5)
summa_stolbcov[:] = a[:].sum(axis = 0)
mean_str = np.zeros(5)
mean_str[:] = a[:].mean(axis = 1)
var_str = np.zeros(5)
var_str[:] = a[:].var(axis = 1)
std_str = np.zeros(5)
std_str[:] = a[:].std(axis = 1)
print('Сумма элементов: ', a_sum, 'Сумма строк: ',summa_strok, 'Сумма столбцов: ', summa_stolbcov, 
      'Среднее по строкам: ', mean_str, 'дисперсия по строкам: ', var_str, 'Станд. Отклонение по строкам: ', std_str, sep = '\n')

Сумма элементов: 
12.176293638104866
Сумма строк: 
[3.33772406 2.77429548 2.64908224 0.62882559 2.78636627]
Сумма столбцов: 
[2.64352075 2.23809357 2.44694825 2.65700417 2.1907269 ]
Среднее по строкам: 
[0.66754481 0.5548591  0.52981645 0.12576512 0.55727325]
дисперсия по строкам: 
[0.05893009 0.13871179 0.10627515 0.0052708  0.04909031]
Станд. Отклонение по строкам: 
[0.2427552  0.37244032 0.3259987  0.07260025 0.22156334]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [98]:
a = np.random.random(size = (5,5))
a[::] = (a[::] - a.mean(axis = 1))/a.std(axis = 1)
a

array([[-0.05318977,  1.01161159,  0.84273693, -0.33314517,  2.33703792],
       [ 0.9572822 ,  1.11853803, -2.00097075,  0.57373586, -1.20423766],
       [-0.46194436,  1.02934159,  0.71045061, -1.20737539,  4.44440656],
       [-2.99141353,  0.94566609, -0.42460679, -0.00490092,  0.20026187],
       [-2.48433459, -1.21889824, -1.17949858, -0.04936275,  0.7935068 ]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [117]:
a = np.random.random(size = (5,5))
print(a)
a[np.argsort(a[:,2], axis = 0)]

[[0.20321093 0.3585186  0.1036852  0.59655088 0.3259536 ]
 [0.76160557 0.40653226 0.55772008 0.61844167 0.9477477 ]
 [0.3614505  0.03042852 0.2555863  0.31486243 0.67497259]
 [0.04076127 0.69974077 0.47559384 0.20697545 0.1192462 ]
 [0.60746614 0.631023   0.00312756 0.38264232 0.37041407]]


array([[0.60746614, 0.631023  , 0.00312756, 0.38264232, 0.37041407],
       [0.20321093, 0.3585186 , 0.1036852 , 0.59655088, 0.3259536 ],
       [0.3614505 , 0.03042852, 0.2555863 , 0.31486243, 0.67497259],
       [0.04076127, 0.69974077, 0.47559384, 0.20697545, 0.1192462 ],
       [0.76160557, 0.40653226, 0.55772008, 0.61844167, 0.9477477 ]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [9]:
#Матрица А должна быть квадратной для извлечения детерминанта в будущем
a = np.random.randint(1, 10, size = (3,3))
b = np.dot(a.T,a)
c = np.dot(a,a.T)
print('B: ',b)
print('C: ',c)
print('Сходство в том, что они квадратные, отличие в размерности - размер B зависит от количества столбцов, а размер С - от количества строк матрицы А')

B:  [[177 159 138]
 [159 153 126]
 [138 126 116]]
C:  [[166 134 158]
 [134 116 132]
 [158 132 164]]
Сходство в том, что они квадратные, отличие в размерности - размер B зависит от количества столбцов, а размер С - от количества строк матрицы А


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [10]:
Sum_diag_b = np.trace(b)
Sum_diag_c = np.trace(c)
print(Sum_diag_b)
print(Sum_diag_c)

446
446


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [12]:
a_det = np.linalg.det(a)
b_det = np.linalg.det(b)
c_det = np.linalg.det(c)
b_sz = np.linalg.eig(b)
c_sz = np.linalg.eig(c)
print('Детерминант А:', a_det,'Детерминант В:',b_det,'Детерминант С:',c_det,'Соб. значения В',b_sz,
      'Соб. значения С',c_sz, sep = '\n')
print('Вывод - набор собственных значений у матриц В и С по значениям аналогичен, но по порядку различен')

Детерминант А:
-119.99999999999997
Детерминант В:
14399.999999999995
Детерминант С:
14399.999999999995
Соб. значения В
(array([434.19224662,   4.60359695,   7.20415643]), array([[ 0.63342667,  0.7656019 ,  0.11235826],
       [ 0.58508623, -0.37884369, -0.71704362],
       [ 0.50640375, -0.51993382,  0.68791283]]))
Соб. значения С
(array([434.19224662,   7.20415643,   4.60359695]), array([[-0.61131708, -0.57353789,  0.54529415],
       [-0.50887379, -0.2428207 , -0.82588472],
       [-0.60608489,  0.78236334,  0.14341796]]))
Вывод - набор собственных значений у матриц В и С по значениям аналогичен, но по порядку различен


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [13]:
np.random.seed(1032192919)
varik = np.random.randint(10)
varik

7

In [14]:
x = np.linspace(2, 3, 100)
y = 1/(x**2-2*x-8)


def metod_trapecii(y,x):
    return np.trapz(y,x)


metod_trapecii(y,x)

-0.1527162166666592